In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv('c:\\Users\\siddh\\Downloads\\archive\\tb.csv')
print(df.to_string())

    Unnamed: 0                    Player       Span   Mat  Inns  NO   Runs    HS    Ave  100  50   0
0            0      SR Tendulkar (INDIA)  1989-2013   200   329  33  15921  248*  53.78   51  68  14
1            1          RT Ponting (AUS)  1995-2012   168   287  29  13378   257  51.85   41  62  17
2            2        JH Kallis (ICC/SA)  1995-2013   166   280  40  13289   224  55.37   45  58  16
3            3      R Dravid (ICC/INDIA)  1996-2012   164   286  32  13288   270  52.31   36  63   8
4            4             AN Cook (ENG)  2006-2018   161   291  16  12472   294  45.35   33  57   9
5            5        KC Sangakkara (SL)  2000-2015   134   233  17  12400   319  57.40   38  52  11
6            6          BC Lara (ICC/WI)  1990-2006   131   232   6  11953  400*  52.88   34  48  17
7            7        S Chanderpaul (WI)  1994-2015   164   280  49  11867  203*  51.37   30  66  15
8            8     DPMD Jayawardene (SL)  1997-2014   149   252  15  11814   374  49.84   34  50  15
9            9           AR Border (AUS)  1978-1994   156   265  44  11174   205  50.56   27  63  11
10          10            SR Waugh (AUS)  1985-2004   168   260  46  10927   200  51.06   32  50  22
11          11       SM Gavaskar (INDIA)  1971-1987   125   214  16  10122  236*  51.12   34  45  12
12          12         Younis Khan (PAK)  2000-2017   118   213  19  10099   313  52.05   34  33  19
13          13             JE Root (ENG)  2012-2021  111*   202  15   9367   254  50.09   23  51   9
14          14              HM Amla (SA)  2004-2019   124   215  16   9282  311*  46.64   28  41  13
15          15         GC Smith (ICC/SA)  2002-2014   117   205  13   9265   277  48.25   27  38  11
16          16            GA Gooch (ENG)  1975-1995   118   215   6   8900   333  42.58   20  46  13
17          17       Javed Miandad (PAK)  1976-1993   124   189  21   8832  280*  52.57   23  43   6
18          18  Inzamam-ul-Haq (ICC/PAK)  1992-2007   120   200  22   8830   329  49.60   25  46  15
19          19        VVS Laxman (INDIA)  1996-2012   134   225  34   8781   281  45.97   17  56  14
20          20       AB de Villiers (SA)  2004-2018   114   191  18   8765  278*  50.66   22  46   8
21          21           MJ Clarke (AUS)  2004-2015   115   198  22   8643  329*  49.10   28  27   9
22          22           ML Hayden (AUS)  1994-2009   103   184  14   8625   380  50.73   30  29  14
23          23      V Sehwag (ICC/INDIA)  2001-2013   104   180   6   8586   319  49.34   23  32  16
24          24         IVA Richards (WI)  1974-1991   121   182  12   8540   291  50.23   24  45  10
25          25          AJ Stewart (ENG)  1990-2003   133   235  21   8463   190  39.54   15  45  14
26          26            DI Gower (ENG)  1978-1992   117   204  18   8231   215  44.25   18  39   7
27          27        KP Pietersen (ENG)  2005-2014   104   181   8   8181   227  47.28   23  35  10
28          28           G Boycott (ENG)  1964-1982   108   193  23   8114  246*  47.72   22  42  10
29          29            GS Sobers (WI)  1954-1974    93   160  21   8032  365*  57.78   26  30  12
30          30            ME Waugh (AUS)  1991-2002   128   209  17   8029  153*  41.81   20  47  19
31          31           V Kohli (INDIA)  2011-2021    97   164  10   7801  254*  50.65   27  27  14
32          32         MA Atherton (ENG)  1989-2001   115   212   7   7728  185*  37.69   16  46  20
33          33             IR Bell (ENG)  2004-2015   118   205  24   7727   235  42.69   22  46  14
34          34           JL Langer (AUS)  1993-2007   105   182  12   7696   250  45.27   23  30  11
35          35           SPD Smith (AUS)  2010-2021   79*   141  18   7625   239  61.99   27  32   5
36          36          MC Cowdrey (ENG)  1954-1975   114   188  15   7624   182  44.06   22  38   9
37          37          LRPL Taylor (NZ)  2007-2021   110   193  24   7584   290  44.87   19  35  14
38          38         CG Greenidge (WI)  1974-1991   108   185  16   7558   226  44.72   19  34  11
39          39     Mohammad Yousuf (PAK)  1998-2010    90   156  12   7530   223  52.29   24  33  11
40          40           MA Taylor (AUS)  1989-1999   104   186  13   7525  334*  43.49   19  40   5
41          41             CH Lloyd (WI)  1966-1985   110   175  14   7515  242*  46.67   19  39   4
42          42           DA Warner (AUS)  2011-2021   88*   161   7   7500  335*  48.70   24  32   9
43          43            DL Haynes (WI)  1978-1994   116   202  25   7487   184  42.29   18  39  10
44          44             DC Boon (AUS)  1984-1996   107   190  20   7422   200  43.65   21  32  16
45          45            G Kirsten (SA)  1993-2004   101   176  15   7289   275  45.27   21  34  13
46          46        KS Williamson (NZ)  2010-2021    86   150  14   7272   251  53.47   24  33   9
47          47          WR Hammond (ENG)  1927-1947    85   140  16   7249  336*  58.45   22  24   4
48          48             CH Gayle (WI)  2000-2014   103   182  11   7214   333  42.18   15  37  15
49          49        SC Ganguly (INDIA)  1996-2008   113   188  17   7212   239  42.17   16  35  13
50          50           SP Fleming (NZ)  1994-2008   111   189  10   7172  274*  40.06    9  46  16
51          51         GS Chappell (AUS)  1970-1984    87   151  19   7110  247*  53.86   24  31  12
52          52          AJ Strauss (ENG)  2004-2012   100   178   6   7037   177  40.91   21  27  15
53          53          DG Bradman (AUS)  1928-1948    52    80  10   6996   334  99.94   29  13   7
54          54        ST Jayasuriya (SL)  1991-2007   110   188  14   6973   340  40.07   14  31  15
55          55            L Hutton (ENG)  1937-1955    79   138  15   6971   364  56.67   19  33   5
56          56     DB Vengsarkar (INDIA)  1976-1992   116   185  22   6868   166  42.13   17  35  15
57          57       KF Barrington (ENG)  1955-1968    82   131  15   6806   256  58.67   20  35   5
58          58           GP Thorpe (ENG)  1993-2005   100   179  28   6744  200*  44.66   16  39  12
59          59           Azhar Ali (PAK)  2010-2021    91   169  11   6721  302*  42.53   18  34  18
60          60         CA Pujara (INDIA)  2010-2021    92   156   9   6589  206*  44.82   18  31  10
61          61          BB McCullum (NZ)  2004-2016   101   176   9   6453   302  38.64   12  31  14
62          62          PA de Silva (SL)  1984-2002    93   159  11   6361   267  42.97   20  22   7
63          63           AD Mathews (SL)  2009-2021    92   165  23   6338  200*  44.63   11  37   2
64          64          MEK Hussey (AUS)  2005-2013    79   137  16   6235   195  51.52   19  29  12
65          65            RB Kanhai (WI)  1957-1974    79   137   6   6227   256  47.53   15  28   7
66          66      M Azharuddin (INDIA)  1984-2000    99   147   9   6215   199  45.03   22  21   5
67          67             HH Gibbs (SA)  1996-2008    90   154   7   6167   228  41.95   14  26  11
68          68           RN Harvey (AUS)  1948-1963    79   137  10   6149   205  48.41   21  24   7
69          69      GR Viswanath (INDIA)  1969-1983    91   155  10   6080   222  41.93   14  35  10
70          70        RB Richardson (WI)  1983-1995    86   146  12   5949   194  44.39   16  27   8
71          71            RR Sarwan (WI)  2000-2011    87   154   8   5842   291  40.01   15  31  12
72          72      ME Trescothick (ENG)  2000-2006    76   143  10   5825   219  43.79   14  29  12
73          73         DCS Compton (ENG)  1937-1957    78   131  15   5807   278  50.06   17  28  10
74          74        Saleem Malik (PAK)  1982-1999   103   154  22   5768   237  43.69   15  29  12
75          75           N Hussain (ENG)  1990-2004    96   171  16   5764   207  37.18   14  33  14
76          76            CL Hooper (WI)  1987-2002   102   173  15   5762   233  36.46   13  27  13
77          77          MP Vaughan (ENG)  1999-2008    82   147   9   5719   197  41.44   18  18   9
78          78        AC Gilchrist (AUS)  1999-2008    96   137  20   5570  204*  47.60   17  26  14
79          79       MV Boucher (ICC/SA)  1997-2012   147   206  24   5515   125  30.30    5  35  17
80          80          MS Atapattu (SL)  1990-2007    90   156  15   5502   249  39.02   16  17  22
81          81           TM Dilshan (SL)  1999-2013    87   145  11   5492   193  40.98   16  23  14
82          82       TT Samaraweera (SL)  2001-2013    81   132  20   5462   231  48.76   14  30  11
83          83      FDM Karunaratne (SL)  2012-2021    74   143   5   5454   244  39.52   13  27  12
84          84             MD Crowe (NZ)  1982-1995    77   131  11   5444   299  45.36   17  18   9
85          85            JB Hobbs (ENG)  1908-1930    61   102   7   5410   211  56.94   15  28   4
86          86          KD Walters (AUS)  1965-1981    74   125  14   5357   250  48.26   15  33   4
87          87         IM Chappell (AUS)  1964-1980    75   136  10   5345   196  42.42   14  26  11
88          88            JG Wright (NZ)  1978-1993    82   148   7   5334   185  37.82   12  23   7
89          89           MJ Slater (AUS)  1993-2001    74   131   7   5312   219  42.83   14  21   9
90          90       N Kapil Dev (INDIA)  1978-1994   131   184  15   5248   163  31.05    8  27  16
91          91            WM Lawry (AUS)  1961-1971    67   123  12   5234   210  47.15   13  27   6
92          92       Misbah-ul-Haq (PAK)  2001-2017    75   132  20   5222  161*  46.62   10  39   9
93          93           IT Botham (ENG)  1977-1992   102   161   6   5200   208  33.54   14  22  14
94          94           JH Edrich (ENG)  1963-1976    77   127   9   5138  310*  43.54   12  24   6
95          95          A Ranatunga (SL)  1982-2000    93   155  12   5105  135*  35.69    4  38  12
96          96        Zaheer Abbas (PAK)  1969-1985    78   124  11   5062   274  44.79   12  20  10

In [3]:
import pandas as pd
import numpy as np
df=pd.read_csv('c:\\Users\\siddh\\Downloads\\archive\\tb.csv')
print(df.head())

   Unnamed: 0                Player       Span  Mat  Inns  NO   Runs    HS  \
0           0  SR Tendulkar (INDIA)  1989-2013  200   329  33  15921  248*
1           1      RT Ponting (AUS)  1995-2012  168   287  29  13378   257
2           2    JH Kallis (ICC/SA)  1995-2013  166   280  40  13289   224
3           3  R Dravid (ICC/INDIA)  1996-2012  164   286  32  13288   270
4           4         AN Cook (ENG)  2006-2018  161   291  16  12472   294

     Ave  100  50   0
0  53.78   51  68  14
1  51.85   41  62  17
2  55.37   45  58  16
3  52.31   36  63   8
4  45.35   33  57   9

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('c:\\Users\\siddh\\Downloads\\archive\\tb.csv')
print(df.tail())
print(df.info())
print(df.describe())

    Unnamed: 0               Player       Span  Mat  Inns  NO  Runs    HS  \
92          92  Misbah-ul-Haq (PAK)  2001-2017   75   132  20  5222  161*
93          93      IT Botham (ENG)  1977-1992  102   161   6  5200   208
94          94      JH Edrich (ENG)  1963-1976   77   127   9  5138  310*
95          95     A Ranatunga (SL)  1982-2000   93   155  12  5105  135*
96          96   Zaheer Abbas (PAK)  1969-1985   78   124  11  5062   274

      Ave  100  50   0
92  46.62   10  39   9
93  33.54   14  22  14
94  43.54   12  24   6
95  35.69    4  38  12
96  44.79   12  20  10
<class 'pandas.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  97 non-null     int64
 1   Player      97 non-null     str
 2   Span        97 non-null     str
 3   Mat         97 non-null     str
 4   Inns        97 non-null     int64
 5   NO          97 non-null     int64
 6   Runs        97 non-null     int64
 7   HS          97 non-null     str
 8   Ave         97 non-null     float64
 9   100         97 non-null     int64
 10  50          97 non-null     int64
 11  0           97 non-null     int64
dtypes: float64(1), int64(7), str(4)
memory usage: 9.2 KB
None

In [6]:
import pandas as pd
import numpy as np
df=pd.read_csv('c:\\Users\\siddh\\Downloads\\archive\\tb.csv')
print("Type:", type(df))
print("Columns:", list(df.columns))
print("Index:", df.index.tolist())

Type: <class 'pandas.DataFrame'>
Columns: ['Unnamed: 0', 'Player', 'Span', 'Mat', 'Inns', 'NO', 'Runs', 'HS', 'Ave', '100', '50', '0']
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96]

In [20]:
import pandas as pd
import numpy as np
df.to_csv("c:\\Users\\siddh\\Downloads\\archive\\tb.csv", index=False)

print(df_from_csv)

    Unnamed: 0                Player       Span  Mat  Inns  NO   Runs    HS  \
0            0  SR Tendulkar (INDIA)  1989-2013  200   329  33  15921  248*
1            1      RT Ponting (AUS)  1995-2012  168   287  29  13378   257
2            2    JH Kallis (ICC/SA)  1995-2013  166   280  40  13289   224
3            3  R Dravid (ICC/INDIA)  1996-2012  164   286  32  13288   270
4            4         AN Cook (ENG)  2006-2018  161   291  16  12472   294
..         ...                   ...        ...  ...   ...  ..    ...   ...
92          92   Misbah-ul-Haq (PAK)  2001-2017   75   132  20   5222  161*
93          93       IT Botham (ENG)  1977-1992  102   161   6   5200   208
94          94       JH Edrich (ENG)  1963-1976   77   127   9   5138  310*
95          95      A Ranatunga (SL)  1982-2000   93   155  12   5105  135*
96          96    Zaheer Abbas (PAK)  1969-1985   78   124  11   5062   274

      Ave  100  50   0
0   53.78   51  68  14
1   51.85   41  62  17
2   55.37   45  58  16
3   52.31   36  63   8
4   45.35   33  57   9
..    ...  ...  ..  ..
92  46.62   10  39   9
93  33.54   14  22  14
94  43.54   12  24   6
95  35.69    4  38  12
96  44.79   12  20  10

[97 rows x 12 columns]

In [21]:
import pandas as pd
import numpy as np
df_from_csv = pd.read_csv("C:\\Users\\siddh\\Downloads\\archive\\tb.csv")

print(df_from_csv)

    Unnamed: 0                Player       Span  Mat  Inns  NO   Runs    HS  \
0            0  SR Tendulkar (INDIA)  1989-2013  200   329  33  15921  248*
1            1      RT Ponting (AUS)  1995-2012  168   287  29  13378   257
2            2    JH Kallis (ICC/SA)  1995-2013  166   280  40  13289   224
3            3  R Dravid (ICC/INDIA)  1996-2012  164   286  32  13288   270
4            4         AN Cook (ENG)  2006-2018  161   291  16  12472   294
..         ...                   ...        ...  ...   ...  ..    ...   ...
92          92   Misbah-ul-Haq (PAK)  2001-2017   75   132  20   5222  161*
93          93       IT Botham (ENG)  1977-1992  102   161   6   5200   208
94          94       JH Edrich (ENG)  1963-1976   77   127   9   5138  310*
95          95      A Ranatunga (SL)  1982-2000   93   155  12   5105  135*
96          96    Zaheer Abbas (PAK)  1969-1985   78   124  11   5062   274

      Ave  100  50   0
0   53.78   51  68  14
1   51.85   41  62  17
2   55.37   45  58  16
3   52.31   36  63   8
4   45.35   33  57   9
..    ...  ...  ..  ..
92  46.62   10  39   9
93  33.54   14  22  14
94  43.54   12  24   6
95  35.69    4  38  12
96  44.79   12  20  10

[97 rows x 12 columns]

In [22]:
import pandas as pd
import numpy as np
df.to_json("C:\\Users\\siddh\\Downloads\\archive\\tb.json", orient="records")
df_from_json = pd.read_json("C:\\Users\\siddh\\Downloads\\archive\\tb.json")
print(df_from_json)

    Unnamed: 0                Player       Span  Mat  Inns  NO   Runs    HS  \
0            0  SR Tendulkar (INDIA)  1989-2013  200   329  33  15921  248*
1            1      RT Ponting (AUS)  1995-2012  168   287  29  13378   257
2            2    JH Kallis (ICC/SA)  1995-2013  166   280  40  13289   224
3            3  R Dravid (ICC/INDIA)  1996-2012  164   286  32  13288   270
4            4         AN Cook (ENG)  2006-2018  161   291  16  12472   294
..         ...                   ...        ...  ...   ...  ..    ...   ...
92          92   Misbah-ul-Haq (PAK)  2001-2017   75   132  20   5222  161*
93          93       IT Botham (ENG)  1977-1992  102   161   6   5200   208
94          94       JH Edrich (ENG)  1963-1976   77   127   9   5138  310*
95          95      A Ranatunga (SL)  1982-2000   93   155  12   5105  135*
96          96    Zaheer Abbas (PAK)  1969-1985   78   124  11   5062   274

      Ave  100  50   0
0   53.78   51  68  14
1   51.85   41  62  17
2   55.37   45  58  16
3   52.31   36  63   8
4   45.35   33  57   9
..    ...  ...  ..  ..
92  46.62   10  39   9
93  33.54   14  22  14
94  43.54   12  24   6
95  35.69    4  38  12
96  44.79   12  20  10

[97 rows x 12 columns]

In [23]:
import pandas as pd
import numpy as np
df.to_json("C:\\Users\\siddh\\Downloads\\archive\\tb.json", orient="records")
df_from_json = pd.read_json("C:\\Users\\siddh\\Downloads\\archive\\tb.json")
print("First 3 rows:")
display(df.head(3))

print("\nLast 3 rows:")
display(df.tail(3))

print("\nInfo:")
df.info()

print("\nDescribe:")
display(df.describe())

print("\nShape (rows, columns):", df.shape)

First 3 rows:

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,100,50,0
0,0,SR Tendulkar (INDIA),1989-2013,200,329,33,15921,248*,53.78,51,68,14
1,1,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,41,62,17
2,2,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,45,58,16

Last 3 rows:

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,100,50,0
94,94,JH Edrich (ENG),1963-1976,77,127,9,5138,310*,43.54,12,24,6
95,95,A Ranatunga (SL),1982-2000,93,155,12,5105,135*,35.69,4,38,12
96,96,Zaheer Abbas (PAK),1969-1985,78,124,11,5062,274,44.79,12,20,10

Info:
<class 'pandas.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  97 non-null     int64
 1   Player      97 non-null     str
 2   Span        97 non-null     str
 3   Mat         97 non-null     str
 4   Inns        97 non-null     int64
 5   NO          97 non-null     int64
 6   Runs        97 non-null     int64
 7   HS          97 non-null     str
 8   Ave         97 non-null     float64
 9   100         97 non-null     int64
 10  50          97 non-null     int64
 11  0           97 non-null     int64
dtypes: float64(1), int64(7), str(4)
memory usage: 9.2 KB

Describe:

,Unnamed: 0,Inns,NO,Runs,Ave,100,50,0
count,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000
mean,48.000000,179.319588,16.103093,7595.690722,46.760722,20.587629,35.597938,11.391753
std,28.145456,44.778284,8.745814,2222.643768,8.164867,8.219328,11.477024,4.172221
min,0.000000,80.000000,5.000000,5062.000000,30.300000,4.000000,13.000000,2.000000
25%,24.000000,147.000000,10.000000,5825.000000,42.290000,15.000000,27.000000,9.000000
50%,48.000000,176.000000,15.000000,7214.000000,45.350000,19.000000,33.000000,11.000000
75%,72.000000,202.000000,20.000000,8540.000000,50.650000,24.000000,42.000000,14.000000
max,96.000000,329.000000,49.000000,15921.000000,99.940000,51.000000,68.000000,22.000000

Shape (rows, columns): (97, 12)

In [ ]:
import pandas as pd
import numpy as np
df.to_json("C:\\Users\\siddh\\Downloads\\archive\\tb.json", orient="records")
df_from_json = pd.read_json("C:\\Users\\siddh\\Downloads\\archive\\tb.json")
print("loc example (rows 0-4, specific columns):")
display(df.loc[0:4, ["Player","Span","Mat","Runs"]])

loc example (rows 0-4, specific columns):

                 Player       Span  Mat   Runs
0  SR Tendulkar (INDIA)  1989-2013  200  15921
1      RT Ponting (AUS)  1995-2012  168  13378
2    JH Kallis (ICC/SA)  1995-2013  166  13289
3  R Dravid (ICC/INDIA)  1996-2012  164  13288
4         AN Cook (ENG)  2006-2018  161  12472

In [28]:
import pandas as pd
import numpy as np
df.to_json("C:\\Users\\siddh\\Downloads\\archive\\tb.json", orient="records")
df_from_json = pd.read_json("C:\\Users\\siddh\\Downloads\\archive\\tb.json")
print("\niloc example (first 3 rows, first 3 columns):")
display(df.iloc[0:3, 0:3])

# Boolean indexing: filter rows where Region is 'East'
print("\nBoolean indexing (Region == 'East'):")
display(df[df["Region"] == "East"])

iloc example (first 3 rows, first 3 columns):

   Unnamed: 0                Player       Span
0           0  SR Tendulkar (INDIA)  1989-2013
1           1      RT Ponting (AUS)  1995-2012
2           2    JH Kallis (ICC/SA)  1995-2013

Boolean indexing (Region == 'East'):

KeyError: 'Region'